title: Graham 的数学花园
subtitle: 知识像花园一样成长、绽放
description: 系统性的数学知识整理与科普
baseurl: "/math-garden"
url: "https://claws-x.github.io"

theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  math_engine: mathjax
